//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// PipeProbeSetting.rc で使用
//
#define IDD_PIPEPROBE_SETTING_MAIN_DIALOG 102
#define IDD_PROPPAGE_CHILD              107
#define IDD_PROPPAGE_GENELAL            109
#define IDD_PROPPAGE_LOG_FILE           110
#define IDD_PROPPAGE_LOG_VIEW           111
#define IDD_PROPPAGE_REGEX_TEST         112
#define IDD_PROPPAGE                    113
#define IDD_PROPPAGE_STRFTIME_DESCRIPTION 114
#define IDR_MAINFRAME                   128
#define IDS_STRING_STRFTIME_DESCRIPTION 145
#define IDC_TAB_MAIN                    1000
#define IDC_EDIT_ADDTIONAL_COMMAND_OPTION_BACK 1002
#define IDC_STATIC_COMMAND_PREVIEW      1003
#define IDC_BUTTON_COMMAND_PREVIEW      1006
#define IDC_CHECK_CREATE_LOG            1009
#define IDC_STATIC_CHILD_PATHNAME       1009
#define IDC_BUTTON_CHILD_SELECT         1010
#define IDC_BUTTON_SELECT_LOG_DIR       1010
#define IDC_STATIC_LOG_DIR              1011
#define IDC_EDIT_ADDTIONAL_COMMAND_OPTION_FRONT 1011
#define IDC_CHECK_USE_ADDTIONAL_COMMAND_OPTION_FRONT 1012
#define IDC_CHECK_USE_ADDTIONAL_COMMAND_OPTION_BACK 1013
#define IDC_CHECK_LOG_FORMAT_DOWN       1013
#define IDC_EDIT_LOG_SEARCH_DOWN        1014
#define IDC_CHECK_LOG_FORMAT_UP         1015
#define IDC_EDIT_LOG_REPLACE_DOWN       1016
#define IDC_EDIT_LOG_SEARCH_UP          1017
#define IDC_CHECK_IGNORE_PARENT_COMMAND_OPTION 1018
#define IDC_EDIT_LOG_REPLACE_UP         1018
#define IDC_CHECK_LOG_VIEW_FORMING_DOWN 1022
#define IDC_CHECK_LOG_VIEW_FORMING_UP   1023
#define IDC_EDIT_LOG_VIEW_SERCH_DOWN    1024
#define IDC_EDIT_LOG_VIEW_FORMING_DOWN  1025
#define IDC_EDIT_LOG_VIEW_SERCH_UP      1026
#define IDC_EDIT_LOG_VIEW_FORMING_UP    1027
#define IDC_BUTTON_SAVE_SETTING_FILE    1028
#define IDC_EDIT_REGEX_SOURCE_STRING    1029
#define IDC_EDIT_REGEX_SEARCH_STRING    1030
#define IDC_EDIT_REGEX_REPLACE_STRING   1031
#define IDC_EDIT_REGEX_RESULT_STRING    1032
#define IDC_BUTTON_EXECUTE_REGEX        1033
#define IDC_BUTTON_SAVE_PROFILE_AS      1035
#define IDC_BUTTON_LOAD_EXISTING_SETTING_FILE 1037
#define IDC_STATIC_SETTING_FILE_PATHNAME 1044
#define IDC_CHECK_LOG_WRITE_COMMAND     1046
#define IDC_BUTTON_SELECT_SOURCE_PIPEPROBE_PATHNAME 1052
#define IDC_STATIC_PIPEPROBE_SOURCE_PATHNAME 1053
#define IDC_STATIC_NAME_PREVIEW         1057
#define IDC_EDIT_LOG_NAME_FORMAT        1059
#define IDC_BUTTON_MAKE_FILENAME        1060
#define IDC_EDIT_MAX_LINE               1061
#define IDC_SPIN_MAX_LINE               1062
#define IDC_BUTTON_TEST_EXECUTE         1063
#define IDC_RADIO_STARTUP_WINDOW        1065
#define IDC_RADIO_STARTUP_ICON          1066
#define IDC_RADIO_STARTUP_TASKTRAY      1067
#define IDC_EDIT_STRFTIME_DESCRIPTION   1072
#define IDC_STATIC_EXE_PATHNAME         1075
#define IDC_BUTTON_INSTALL_EXE          1076

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        146
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         1077
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
