//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// MasteringWinSock.rc で使用
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MASTERINGWINSOCK_DIALOG     102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDC_IPADDRESS_LISTEN            1000
#define IDC_SPIN_LISTEN_ADDRESS         1001
#define IDC_EDIT_LISTEN_PORT            1002
#define IDC_SPIN_LISTEN_PORT            1003
#define IDC_IPADDRESS_CLI               1004
#define IDC_SPIN_CLI_ADDRESS            1005
#define IDC_EDIT_CLI_PORT               1006
#define IDC_SPIN_CLI_PORT               1007
#define IDC_IPADDRESS_CONNECT_TO_ADDRESS 1008
#define IDC_SPIN_CONNECT_TO_ADDRESS     1009
#define IDC_EDIT_CONNECT_TO_PORT        1010
#define IDC_SPIN_CONNECT_TO_PORT        1011
#define IDC_LIST_LISTEN_CREATE          1012
#define IDC_LIST_CLI_CREATE             1013
#define IDC_LIST_LISTEN_WAIT_ACCEPT     1014
#define IDC_LIST_SEV_ACCEPTED           1016
#define IDC_LIST_CLI_ACCEPTED           1017
#define IDC_BUTTON_LISTEN_CREATE        1018
#define IDC_BUTTON_LISTEN_LISTEN        1019
#define IDC_BUTTON_LISTEN_CLOSE         1020
#define IDC_BUTTON_LISTEN_DELETE        1021
#define IDC_BUTTON_ACCEPT               1022
#define IDC_BUTTON_WAITING_ACCEPT_CLOSE 1023
#define IDC_BUTTON_SEV_CONNECTING_CLOSE 1024
#define IDC_BUTTON_SEV_CONNECTING_DELETE 1025
#define IDC_BUTTON_CLI_CONNECT          1026
#define IDC_BUTTON_CLI_CONNECTING_DELETE 1030
#define IDC_EDIT_SEV_BINARY_FOR_SENDING 1031
#define IDC_BUTTON_CLI_CREATE           1032
#define IDC_BUTTON_CLI_DELETE           1033
#define IDC_BUTTON_SEV_SEND_BINARY      1034
#define IDC_EDIT_SEV_TEXT_FOR_SENDING   1035
#define IDC_BUTTON_SEV_SEND_TEXT        1036
#define IDC_BUTTON_CLI_SEND_BINARY      1038
#define IDC_EDIT_CLI_TEXT_FOR_SENDING   1039
#define IDC_BUTTON_CLI_SEND_TEXT        1040
#define IDC_EDIT_SEV_RECEIVED_BINARY    1041
#define IDC_EDIT_SEV_RECEIVED_TEXT      1042
#define IDC_BUTTON_WAITING_ACCEPT_DELETE 1043
#define IDC_BUTTON_CLI_CONNECTING_CLOSE 1044
#define IDC_EDIT_CLI_BINARY_FOR_SENDING 1046
#define IDC_BUTTON_LISTEN_NEW           1047
#define IDC_BUTTON_CLI_NEW              1048
#define IDC_BUTTON_CLI_CLOSE            1049
#define IDC_BUTTON_SEV_NEW              1050
#define IDC_EDIT_CLI_RECEIVED_BINARY    1051
#define IDC_EDIT_CLI_RECEIVED_TEXT      1052
#define IDC_LIST_SEV_CREATE             1053
#define IDC_BUTTON_SEV_DELETE           1055
#define IDC_BUTTON_SEV_CREATE           1056
#define IDC_BUTTON_SEV_CLOSE            1057
#define IDC_BUTTON_SEV_CONNECTING_RECEIVE 1058
#define IDC_BUTTON_CLI_CONNECTING_RECEIVE 1059
#define IDC_BUTTON_SEV_CLEAR_TEXT       1060
#define IDC_BUTTON_CLI_CLEAR_TEXT       1061
#define IDC_BUTTON_SEV_CONNECTING_SHUTDOWN 1062
#define IDC_BUTTON_CLI_CONNECTED_SHUTDOWN 1063
#define IDC_BUTTON_LISTEN_SHUTDOWN      1064
#define IDC_BUTTON_CLI_SHUTDOWN         1065
#define IDC_BUTTON_SEV_SHUTDOWN         1066
#define IDC_RADIO_SHUTDOWN_FLAG_RECEIVES 1070
#define IDC_RADIO_SHUTDOWN_FLAG_SENDS   1071
#define IDC_RADIO_SHUTDOWN_FLAG_BOTH    1072
#define IDC_COMBO_CLI_BYNARY_FOR_SENDING 1073
#define IDC_COMBO_SEV_BINARY_FOR_SENDING 1074
#define IDC_COMBO_SEV_TEXT_FOR_SENDING  1075
#define IDC_COMBO3                      1076
#define IDC_COMBO_CLI_TEXT_FOR_SENDING  1076
#define IDC_CHECK_SOCKET_BUFFER_CHANGE_FROM_DEFAULT_BUFFER_SIZE 1077
#define IDC_EDIT_SOCKET_BUFFER_SIZE     1078
#define IDC_SPIN_BUFFER_SIZE            1079
#define IDC_SPIN_SOCKET_BUFFER_SIZE     1079

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1080
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
